spring.application.name=armin

# PORT DYNAMIQUE
server.port=${PORT:8081}

# POSTGRESQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/armin_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=28800000
application.security.jwt.refresh-token-expiration=604800000

# GMAIL / SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
application.mail.from=${MAIL_USERNAME}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# IA
gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}

# FEDAPAY
fedapay.api.secret-key=${FEDAPAY_SECRET_KEY}
fedapay.api.base-url=https://sandbox-api.fedapay.com
fedapay.callback-url=${BACKEND_URL:http://localhost:8081}/api/webhooks/fedapay

# JPA / THYMELEAF
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# FRONTEND
application.mailing.frontend.activation-url=https://armin-tg.vercel.app/confirm

# SWAGGER
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html